spring.application.name=dna
server.port=8080
dna.dataset.path=../../Dataset/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna
dna.chunk.size=250000
dna.benchmark.sample.bases=1000000
dna.quick.scan.bases=5000000
